language: node_js
node_js:
    - '10'
dist: xenial
sudo: required
addons:
    chrome: stable # have Travis install Chrome stable.
script:
    - npm test
    - npm run build
branches:
    only:
        - master
